version: "3.2"

services:
  api:
    build: .
    container_name: api
    hostname: api
    environment:
      - PORT=5000
      - HOST="0.0.0.0"
    ports:
      - 5000:5000
    command: ["uvicorn", "app.main:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "5000"]
